#ifndef RULES_H
#define RULES_H

#define RULE_PROGRAM 1
#define RULE_DECLARATIONS  2
#define RULE_DECLARATION 4
#define RULE_CLASS 5

#define RULE_CLASS_SCALAR 9
#define RULE_TYPE 10
#define RULE_CLASS_VECTOR 15
#define RULE_IDENTIFIERS 18
#define RULE_FUNCTIONS 20
#define RULE_FUNCTION 22
#define RULE_FUNCTION_PARAMS 23
#define RULE_FUNCTION_REMAIN_PARAMS 25
#define RULE_FUNCTION_PARAM 27
#define RULE_FUNCTION_DECLARE 28
#define RULE_STATEMENTS 30
#define RULE_STATEMENT 32
#define RULE_STATEMENT_SIMPLE 34

#define RULE_BLOCK 40
#define RULE_ASSIGNMENT 43
#define RULE_ARRAY_ELEM 48
#define RULE_CONDITIONAL 50
#define RULE_LOOP 52
#define RULE_READING 54
#define RULE_WRITING 56

#define RULE_FUNCTION_RETURN 61
#define RULE_EXP 72
#define RULE_EXP_LIST 89
#define RULE_EXP_REM_LIST 91
#define RULE_COMP 93
#define RULE_CONST 99
#define RULE_CONST_LOGIC 102
#define RULE_CONST_INT 104
#define RULE_NUMBER 105
#define RULE_IDENTIFIER 108
#define RULE_IDENTIFIER_QUEUE 110
#define RULE_ALFANUMERIC 112
#define RULE_LETTER 114
#define RULE_DIGIT 115

#endif