[GLOBAL]
SRCDIR=./src  # source directory
INCDIR=./inc  # include directory
OBJDIR=./obj  # object directory
DISTDIR=./out  # distribution dir
CFLAGS=[ -ansi, -g, -Wall ]  # compilation flags
LDFLAGS=[ -lm ]  # link flags
DIST_IGNORE=[ ./out/*.zip, ./obj/*.o ]  # files to be ignored when distribuiting
DEFAULT_ENV=p1  # default environment
CLOG=CHANGELOG.md # changelog file

[p1]
TARGET=p1
SRCS=[ p1 ]  # dependency modules
